import Link from "next/link";
import { EyeIcon } from "@phosphor-icons/react/dist/ssr";
import { AdminDataTable } from "@/components/admin/admin-data-table";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { requireAdmin } from "@/lib/admin/auth";
import { ADMIN_PAGE_SIZE, parseAdminQuery, type AdminSearchParams } from "@/lib/admin/query";
import { formatIDR } from "@/lib/formatters";
import { prisma } from "@/lib/prisma";

export default async function OrdersPage({ searchParams }: { searchParams: AdminSearchParams }) { await requireAdmin("orders:read"); const query = await parseAdminQuery(searchParams); const statuses = ["PENDING_PAYMENT", "PAID", "PROCESSING", "SHIPPED", "DELIVERED", "CANCELLED", "REFUNDED"] as const; const where = { ...(query.q ? { OR: [{ orderNumber: { contains: query.q, mode: "insensitive" as const } }, { customerName: { contains: query.q, mode: "insensitive" as const } }, { customerEmail: { contains: query.q, mode: "insensitive" as const } }] } : {}), ...(statuses.includes(query.status as typeof statuses[number]) ? { status: query.status as typeof statuses[number] } : {}) }; const orderBy = query.sort === "total-high" ? { grandTotal: "desc" as const } : { placedAt: "desc" as const }; const [orders, total] = await prisma.$transaction([prisma.order.findMany({ where, orderBy, skip: (query.page - 1) * ADMIN_PAGE_SIZE, take: ADMIN_PAGE_SIZE, include: { _count: { select: { items: true } } } }), prisma.order.count({ where })]); return <div><AdminPageHeader title="Orders" description="Cari, filter, perbarui fulfillment, dan pantau pembayaran serta pengiriman." breadcrumbs={[{ label: "Orders" }]} /><AdminDataTable columns={[{ key: "order", label: "Order" }, { key: "customer", label: "Customer" }, { key: "items", label: "Items" }, { key: "total", label: "Total" }, { key: "payment", label: "Payment" }, { key: "status", label: "Status" }, { key: "action", label: "" }]} rows={orders.map((order) => ({ id: order.id, cells: { order: <div><p className="font-semibold">{order.orderNumber}</p><p className="text-xs text-muted-foreground">{new Intl.DateTimeFormat("id-ID", { dateStyle: "medium" }).format(order.placedAt)}</p></div>, customer: <div><p>{order.customerName}</p><p className="text-xs text-muted-foreground">{order.customerEmail}</p></div>, items: order._count.items, total: formatIDR(Number(order.grandTotal)), payment: <Badge variant="outline">{order.paymentStatus}</Badge>, status: <Badge variant="secondary">{order.status.replaceAll("_", " ")}</Badge>, action: <Button asChild size="icon-sm" variant="ghost"><Link href={`/admin/orders/${order.id}`} aria-label={`View ${order.orderNumber}`}><EyeIcon aria-hidden /></Link></Button> } }))} page={query.page} total={total} totalPages={Math.max(1, Math.ceil(total / ADMIN_PAGE_SIZE))} filters={statuses.map((status) => ({ value: status, label: status.replaceAll("_", " ") }))} sortOptions={[{ value: "newest", label: "Newest" }, { value: "total-high", label: "Highest total" }]} /></div>; }
