import { AdminDataTable } from "@/components/admin/admin-data-table";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { PayoutControl } from "@/components/admin/payout-control";
import { Badge } from "@/components/ui/badge";
import type { PayoutStatus } from "@/generated/prisma/client";
import { requireAdmin } from "@/lib/admin/auth";
import { ADMIN_PAGE_SIZE, parseAdminQuery, type AdminSearchParams } from "@/lib/admin/query";
import { formatIDR } from "@/lib/formatters";
import { prisma } from "@/lib/prisma";

const statuses: PayoutStatus[] = ["REQUESTED", "PROCESSING", "PAID", "FAILED", "CANCELLED"];
export default async function PayoutsPage({ searchParams }: { searchParams: AdminSearchParams }) { await requireAdmin("payouts:read"); const query = await parseAdminQuery(searchParams); const status = statuses.includes(query.status as PayoutStatus) ? query.status as PayoutStatus : undefined; const where = { ...(status ? { status } : {}), ...(query.q ? { OR: [{ payoutNumber: { contains: query.q, mode: "insensitive" as const } }, { seller: { displayName: { contains: query.q, mode: "insensitive" as const } } }] } : {}) }; const [payouts, total] = await prisma.$transaction([prisma.payout.findMany({ where, orderBy: { requestedAt: "desc" }, skip: (query.page - 1) * ADMIN_PAGE_SIZE, take: ADMIN_PAGE_SIZE, include: { seller: true, _count: { select: { items: true } } } }), prisma.payout.count({ where })]); return <div><AdminPageHeader title="Seller payouts" description="Nilai pencairan berasal dari komisi eligible yang dihitung server." breadcrumbs={[{ label: "Sellers", href: "/admin/sellers" }, { label: "Payouts" }]} /><AdminDataTable columns={[{ key: "payout", label: "Payout" }, { key: "seller", label: "Seller" }, { key: "amount", label: "Amount" }, { key: "items", label: "Items" }, { key: "status", label: "Status" }, { key: "action", label: "Action" }]} rows={payouts.map((item) => ({ id: item.id, cells: { payout: <div><p className="font-semibold">{item.payoutNumber}</p><p className="text-xs text-muted-foreground">{item.requestedAt.toLocaleDateString("id-ID")}</p></div>, seller: item.seller.displayName, amount: formatIDR(Number(item.amount)), items: item._count.items, status: <Badge variant="outline">{item.status}</Badge>, action: <PayoutControl id={item.id} status={item.status} /> } }))} page={query.page} total={total} totalPages={Math.max(1, Math.ceil(total / ADMIN_PAGE_SIZE))} filters={statuses.map((value) => ({ value, label: value }))} /></div>; }
