"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { BankIcon, SpinnerGapIcon } from "@phosphor-icons/react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { formatIDR } from "@/lib/formatters";
export function PayoutRequest({ items }: { items: { id: string; label: string; amount: number }[] }) { const router = useRouter(); const [selected, setSelected] = useState(items.map((item) => item.id)); const [busy, setBusy] = useState(false); const amount = items.filter((item) => selected.includes(item.id)).reduce((sum, item) => sum + item.amount, 0); async function request() { setBusy(true); try { const response = await fetch("/api/seller/payouts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ commissionIds: selected }) }); const result = await response.json() as { success?: boolean; error?: { message?: string } }; if (!result.success) throw new Error(result.error?.message); toast.success("Payout berhasil diajukan."); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Payout gagal."); } finally { setBusy(false); } } return <section className="border border-[#ddd5c7] bg-[#faf8f3] p-5 sm:p-7"><h2 className="font-serif text-2xl">Available commissions</h2><div className="mt-5 divide-y divide-[#ddd5c7]">{items.map((item) => <label key={item.id} className="flex items-center gap-3 py-4"><Checkbox checked={selected.includes(item.id)} onCheckedChange={(checked) => setSelected((current) => checked ? [...current, item.id] : current.filter((id) => id !== item.id))} /><span className="flex-1 text-sm">{item.label}</span><span className="text-sm font-semibold">{formatIDR(item.amount)}</span></label>)}</div><div className="mt-5 flex items-center justify-between border-t border-[#bbb09d] pt-5"><div><p className="text-xs tracking-wider uppercase">Requested total</p><p className="mt-1 font-serif text-3xl">{formatIDR(amount)}</p></div><Button disabled={!selected.length || busy} onClick={() => void request()}>{busy ? <SpinnerGapIcon className="animate-spin" aria-hidden /> : <BankIcon aria-hidden />}Request payout</Button></div></section>; }
