"use client";

import { useState } from "react";
import { PlusIcon, TrashIcon } from "@phosphor-icons/react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type Address = { id: string; label: string; recipient: string; phone: string; line1: string; line2: string | null; district: string; city: string; province: string; postalCode: string; country: string; isDefault: boolean };

export function AddressManager({ initialAddresses }: { initialAddresses: Address[] }) {
  const [addresses, setAddresses] = useState(initialAddresses); const [open, setOpen] = useState(false); const [message, setMessage] = useState("");
  async function add(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); const response = await fetch("/api/addresses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, isDefault: values.isDefault === "on" }) }); const result = await response.json() as { success: boolean; data?: Address; error?: { message?: string } }; if (result.success && result.data) { setAddresses((items) => result.data?.isDefault ? [result.data, ...items.map((item) => ({ ...item, isDefault: false }))] : [...items, result.data!]); form.reset(); setOpen(false); } else setMessage(result.error?.message ?? "Alamat gagal disimpan."); }
  async function remove(id: string) { const response = await fetch(`/api/addresses/${id}`, { method: "DELETE" }); if (response.ok) setAddresses((items) => items.filter((item) => item.id !== id)); }
  return <div className="mt-8"><div className="grid gap-4 sm:grid-cols-2">{addresses.map((address) => <article key={address.id} className="relative border border-border bg-background p-5"><div className="flex items-center gap-2"><h2 className="font-serif text-xl">{address.label}</h2>{address.isDefault ? <span className="bg-primary px-2 py-1 text-[0.55rem] tracking-wider text-primary-foreground uppercase">Default</span> : null}</div><p className="mt-4 text-sm font-semibold">{address.recipient}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{address.line1}{address.line2 ? `, ${address.line2}` : ""}<br />{address.district}, {address.city}<br />{address.province} {address.postalCode}<br />{address.phone}</p><button type="button" onClick={() => remove(address.id)} aria-label={`Hapus alamat ${address.label}`} className="absolute top-4 right-4 grid size-9 place-items-center hover:text-destructive"><TrashIcon aria-hidden /></button></article>)}</div><Button variant="outline" className="mt-5" onClick={() => setOpen((value) => !value)}><PlusIcon aria-hidden /> Add address</Button>{open ? <form onSubmit={add} className="mt-6 grid gap-4 border border-border bg-background p-6 sm:grid-cols-2">{[["label", "Label"], ["recipient", "Penerima"], ["phone", "Telepon"], ["line1", "Alamat"], ["line2", "Detail alamat (opsional)"], ["district", "Kecamatan"], ["city", "Kota"], ["province", "Provinsi"], ["postalCode", "Kode pos"]].map(([id, label]) => <div key={id} className={id === "line1" || id === "line2" ? "sm:col-span-2" : ""}><Label htmlFor={id}>{label}</Label><Input id={id} name={id} required={id !== "line2"} className="mt-2" /></div>)}<input type="hidden" name="country" value="Indonesia" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isDefault" /> Jadikan alamat utama</label><div className="sm:col-span-2"><Button type="submit">Save address</Button></div>{message ? <p className="text-sm text-destructive sm:col-span-2">{message}</p> : null}</form> : null}</div>;
}
