import { authorizeAdminApi } from "@/lib/admin/auth";
import { writeAuditLog } from "@/lib/admin/audit";
import { bulkIdsSchema, productAdminSchema } from "@/lib/admin/schemas";
import { apiSuccess, handleApiError } from "@/lib/api-response";
import { prisma } from "@/lib/prisma";
import { invalidateStorefront } from "@/lib/cache-invalidation";

export async function POST(request: Request) {
  try { const auth = await authorizeAdminApi("products:write"); if (!auth.user) return auth.response; const data = productAdminSchema.parse(await request.json()); const product = await prisma.$transaction(async (tx) => { const created = await tx.product.create({ data: { name: data.name, slug: data.slug, baseSku: data.baseSku, categoryId: data.categoryId, brandId: data.brandId, description: data.description, shortDescription: data.shortDescription || null, condition: data.condition, conditionLabel: data.conditionLabel || null, completeness: data.completeness || null, flawNotes: data.flawNotes || null, authenticationStatus: data.authenticationStatus || null, price: data.price, compareAtPrice: data.compareAtPrice, costPrice: data.costPrice, status: data.status, publishedAt: data.status === "ACTIVE" ? new Date() : null, isFeatured: data.isFeatured, isNewArrival: data.isNewArrival, weightGrams: data.weightGrams, images: { create: data.images.map((image, index) => ({ url: image.url, alt: image.alt, width: image.width, height: image.height, isPrimary: image.isPrimary || index === 0, sortOrder: index })) }, variants: { create: data.variants.map((variant) => ({ sku: variant.sku, name: variant.name, color: variant.color || null, colorHex: variant.colorHex || null, size: variant.size || null, price: variant.price, compareAtPrice: variant.compareAtPrice, isActive: variant.isActive, inventory: { create: { quantity: variant.stock, lowStockAt: variant.lowStockAt } } })) } } }); await writeAuditLog(tx, { userId: auth.user.id, action: "PRODUCT_CREATED", entityType: "Product", entityId: created.id, metadata: { name: created.name, status: created.status }, request }); return created; }); invalidateStorefront(); return apiSuccess({ id: product.id, slug: product.slug }, { status: 201 }); } catch (error) { return handleApiError(error); }
}

export async function DELETE(request: Request) {
  try { const auth = await authorizeAdminApi("products:write"); if (!auth.user) return auth.response; const { ids } = bulkIdsSchema.parse(await request.json()); const result = await prisma.$transaction(async (tx) => { const changed = await tx.product.updateMany({ where: { id: { in: ids } }, data: { status: "ARCHIVED", deletedAt: new Date() } }); await writeAuditLog(tx, { userId: auth.user.id, action: "PRODUCTS_BULK_ARCHIVED", entityType: "Product", metadata: { ids }, request }); return changed; }); invalidateStorefront(); return apiSuccess({ count: result.count }); } catch (error) { return handleApiError(error); }
}
