import Link from "next/link";
import { ArrowRightIcon, CurrencyCircleDollarIcon, PackageIcon, ShoppingCartIcon, UsersIcon } from "@phosphor-icons/react/dist/ssr";

import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { SalesChart } from "@/components/admin/sales-chart";
import { Badge } from "@/components/ui/badge";
import { requireAdmin } from "@/lib/admin/auth";
import { formatIDR } from "@/lib/formatters";
import { prisma } from "@/lib/prisma";

export default async function AdminDashboardPage() {
  await requireAdmin("dashboard:read");
  const since = new Date(); since.setMonth(since.getMonth() - 5); since.setDate(1); since.setHours(0, 0, 0, 0);
  const [sales, totalOrders, totalCustomers, pendingOrders, lowStock, recentOrders, orderItems] = await Promise.all([
    prisma.order.findMany({ where: { paymentStatus: { in: ["PAID", "PARTIALLY_REFUNDED"] } }, select: { grandTotal: true, placedAt: true } }),
    prisma.order.count(), prisma.user.count({ where: { role: "CUSTOMER", deletedAt: null } }), prisma.order.count({ where: { status: "PENDING_PAYMENT" } }),
    prisma.inventory.findMany({ where: { quantity: { lte: 2 } }, include: { variant: { include: { product: { include: { brand: true } } } } }, orderBy: { quantity: "asc" }, take: 6 }),
    prisma.order.findMany({ orderBy: { placedAt: "desc" }, take: 6, select: { id: true, orderNumber: true, customerName: true, status: true, grandTotal: true, placedAt: true } }),
    prisma.orderItem.findMany({ where: { order: { paymentStatus: { in: ["PAID", "PARTIALLY_REFUNDED"] } } }, include: { variant: { include: { product: { include: { brand: true } } } } }, take: 1000 }),
  ]);
  const totalSales = sales.reduce((sum, order) => sum + Number(order.grandTotal), 0); const average = totalOrders ? totalSales / totalOrders : 0;
  const months = Array.from({ length: 6 }, (_, offset) => { const date = new Date(); date.setMonth(date.getMonth() - (5 - offset)); return { key: `${date.getFullYear()}-${date.getMonth()}`, label: new Intl.DateTimeFormat("id-ID", { month: "short" }).format(date), value: 0 }; });
  for (const order of sales) { const key = `${order.placedAt.getFullYear()}-${order.placedAt.getMonth()}`; const month = months.find((item) => item.key === key); if (month) month.value += Number(order.grandTotal); }
  const products = aggregate(orderItems, (item) => item.productName); const brands = aggregate(orderItems, (item) => item.variant?.product.brand.name ?? "Unknown");
  return <div><AdminPageHeader title="Commerce overview" description="Ringkasan performa toko, order yang perlu ditangani, dan kesehatan inventori." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total sales" value={formatIDR(totalSales)} icon={CurrencyCircleDollarIcon} /><Metric label="Total orders" value={String(totalOrders)} icon={ShoppingCartIcon} /><Metric label="Customers" value={String(totalCustomers)} icon={UsersIcon} /><Metric label="Average order" value={formatIDR(average)} icon={PackageIcon} /></div><div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(18rem,0.7fr)]"><Panel title="Sales · 6 months"><SalesChart data={months} /></Panel><Panel title="Needs attention"><div className="mt-5 space-y-3"><Attention href="/admin/orders?status=PENDING_PAYMENT" label="Pending orders" value={pendingOrders} /><Attention href="/admin/products?stock=low" label="Low-stock variants" value={lowStock.length} /></div><div className="mt-6 border-t border-[#ded9cf] pt-5">{lowStock.map((item) => <div key={item.id} className="flex justify-between py-2 text-xs"><span className="truncate">{item.variant.product.name} · {item.variant.name}</span><span className="font-semibold">{item.quantity - item.reserved}</span></div>)}</div></Panel></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="Recent orders"><div className="mt-5 divide-y divide-[#e4dfd5]">{recentOrders.map((order) => <Link href={`/admin/orders/${order.id}`} key={order.id} className="flex items-center justify-between gap-4 py-4 hover:text-[#7c693f]"><div><p className="text-sm font-semibold">{order.orderNumber}</p><p className="mt-1 text-xs text-[#77736b]">{order.customerName} · {new Intl.DateTimeFormat("id-ID", { dateStyle: "medium" }).format(order.placedAt)}</p></div><div className="text-right"><p className="text-sm">{formatIDR(Number(order.grandTotal))}</p><Badge variant="outline" className="mt-1">{order.status.replaceAll("_", " ")}</Badge></div></Link>)}</div></Panel><div className="grid gap-6 sm:grid-cols-2"><Ranking title="Top products" rows={products} /><Ranking title="Top brands" rows={brands} /></div></div></div>;
}

function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: typeof PackageIcon }) { return <article className="border border-[#ded9cf] bg-[#faf8f3] p-5"><div className="flex items-center justify-between"><p className="text-[0.625rem] font-semibold tracking-[0.16em] text-[#77736b] uppercase">{label}</p><Icon className="size-5 text-[#9d895c]" aria-hidden /></div><p className="mt-5 font-serif text-3xl">{value}</p></article>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border border-[#ded9cf] bg-[#faf8f3] p-5 sm:p-6"><h2 className="font-serif text-2xl">{title}</h2>{children}</section>; }
function Attention({ href, label, value }: { href: string; label: string; value: number }) { return <Link href={href} className="flex items-center justify-between border border-[#ded9cf] bg-white p-4 text-sm"><span>{label}</span><span className="flex items-center gap-2 font-semibold">{value}<ArrowRightIcon aria-hidden /></span></Link>; }
function Ranking({ title, rows }: { title: string; rows: { name: string; quantity: number }[] }) { return <Panel title={title}><ol className="mt-5 space-y-4">{rows.slice(0, 5).map((row, index) => <li key={row.name} className="flex items-center gap-3 text-sm"><span className="grid size-7 place-items-center rounded-full bg-[#ece5d7] text-xs">{index + 1}</span><span className="min-w-0 flex-1 truncate">{row.name}</span><span className="font-semibold">{row.quantity}</span></li>)}</ol></Panel>; }
function aggregate<T extends { quantity: number }>(items: T[], getName: (item: T) => string) { const map = new Map<string, number>(); for (const item of items) map.set(getName(item), (map.get(getName(item)) ?? 0) + item.quantity); return [...map].map(([name, quantity]) => ({ name, quantity })).sort((a, b) => b.quantity - a.quantity); }
