import { randomUUID } from "node:crypto";
import { apiError, apiSuccess, handleApiError } from "@/lib/api-response";
import { authenticateSellerApi } from "@/lib/seller/auth";
import { logSellerActivity } from "@/lib/seller/activity";
import { calculatePayoutAmount } from "@/lib/seller/domain";
import { payoutRequestSchema } from "@/lib/seller/schemas";
import { prisma } from "@/lib/prisma";

export async function POST(request: Request) { try { const auth = await authenticateSellerApi(); if (!auth.user || !auth.seller) return auth.response; if (!auth.seller.bankName || !auth.seller.bankAccountName || !auth.seller.bankAccountNumber) return apiError("BANK_ACCOUNT_REQUIRED", "Lengkapi rekening payout.", 422); const data = payoutRequestSchema.parse(await request.json()); const commissions = await prisma.commission.findMany({ where: { id: { in: data.commissionIds }, submission: { sellerId: auth.seller.id, status: "COMPLETED" }, sellerNetAmount: { not: null }, payoutItem: null }, include: { submission: true } }); if (commissions.length !== new Set(data.commissionIds).size) return apiError("PAYOUT_ITEM_NOT_ELIGIBLE", "Terdapat item yang belum eligible atau sudah dicairkan.", 409); const amount = calculatePayoutAmount(commissions.map((item) => ({ amount: item.sellerNetAmount! }))); const allEligible = await prisma.commission.findMany({ where: { submission: { sellerId: auth.seller.id, status: "COMPLETED" }, sellerNetAmount: { not: null }, payoutItem: null }, select: { sellerNetAmount: true } }); const before = calculatePayoutAmount(allEligible.map((item) => ({ amount: item.sellerNetAmount! }))); const payout = await prisma.$transaction(async (tx) => { const created = await tx.payout.create({ data: { payoutNumber: `PO-${Date.now()}-${randomUUID().slice(0, 5).toUpperCase()}`, sellerId: auth.seller.id, amount, bankSnapshot: { bankName: auth.seller.bankName, accountName: auth.seller.bankAccountName, accountLast4: auth.seller.bankAccountNumber!.slice(-4) }, items: { create: commissions.map((commission) => ({ commissionId: commission.id, amount: commission.sellerNetAmount! })) } } }); await logSellerActivity(tx, { sellerId: auth.seller.id, actorUserId: auth.user.id, action: "PAYOUT_REQUESTED", entityType: "Payout", entityId: created.id, moneyBefore: before, moneyAfter: before.sub(amount), metadata: { payoutNumber: created.payoutNumber, commissionIds: data.commissionIds } }); return created; }); return apiSuccess({ id: payout.id, payoutNumber: payout.payoutNumber, amount: Number(payout.amount) }, { status: 201 }); } catch (error) { return handleApiError(error); } }
