import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { SalesChart } from "@/components/admin/sales-chart";
import { requireAdmin } from "@/lib/admin/auth";
import { formatIDR } from "@/lib/formatters";
import { prisma } from "@/lib/prisma";

// Server report boundaries intentionally use the request-time clock.
// eslint-disable-next-line react-hooks/purity
export default async function ReportsPage() { await requireAdmin("reports:read"); const since = new Date(Date.now() - 30 * 86400000); const [orders, products, customers, inventory] = await Promise.all([prisma.order.findMany({ where: { placedAt: { gte: since }, paymentStatus: { in: ["PAID", "PARTIALLY_REFUNDED"] } }, select: { grandTotal: true, placedAt: true } }), prisma.orderItem.groupBy({ by: ["productName"], where: { order: { paymentStatus: "PAID" } }, _sum: { quantity: true, lineTotal: true }, orderBy: { _sum: { quantity: "desc" } }, take: 8 }), prisma.user.findMany({ where: { role: "CUSTOMER", createdAt: { gte: since } }, include: { orders: { where: { paymentStatus: "PAID" }, select: { grandTotal: true } } }, take: 10 }), prisma.inventory.findMany({ include: { variant: { include: { product: true } } }, orderBy: { quantity: "asc" }, take: 10 })]); const daily = Array.from({ length: 14 }, (_, offset) => { const date = new Date(); date.setDate(date.getDate() - (13 - offset)); return { key: date.toISOString().slice(0, 10), label: new Intl.DateTimeFormat("id-ID", { day: "2-digit", month: "short" }).format(date), value: 0 }; }); for (const order of orders) { const item = daily.find((day) => day.key === order.placedAt.toISOString().slice(0, 10)); if (item) item.value += Number(order.grandTotal); } return <div><AdminPageHeader title="Reports" description="Ringkasan sales, performa produk, customer acquisition, dan inventory." breadcrumbs={[{ label: "Reports" }]} /><div className="grid gap-6 xl:grid-cols-2"><Panel title="Sales · last 14 days"><SalesChart data={daily} /></Panel><Panel title="Product performance"><ReportTable headers={["Product", "Units", "Revenue"]} rows={products.map((item) => [item.productName, String(item._sum.quantity ?? 0), formatIDR(Number(item._sum.lineTotal ?? 0))])} /></Panel><Panel title="New customers · 30 days"><ReportTable headers={["Customer", "Orders", "Spend"]} rows={customers.map((customer) => [customer.name ?? customer.email, String(customer.orders.length), formatIDR(customer.orders.reduce((sum, order) => sum + Number(order.grandTotal), 0))])} /></Panel><Panel title="Inventory health"><ReportTable headers={["Variant", "On hand", "Reserved"]} rows={inventory.map((item) => [`${item.variant.product.name} · ${item.variant.name}`, String(item.quantity), String(item.reserved)])} /></Panel></div></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="overflow-hidden border border-[#ded9cf] bg-[#faf8f3] p-5 sm:p-6"><h2 className="font-serif text-2xl">{title}</h2>{children}</section>; }
function ReportTable({ headers, rows }: { headers: string[]; rows: string[][] }) { return <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-[#ded9cf]">{headers.map((header) => <th key={header} className="py-3 text-xs tracking-wider uppercase">{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row[0]}-${index}`} className="border-b border-[#e8e3da] last:border-0">{row.map((cell, cellIndex) => <td key={`${cell}-${cellIndex}`} className="py-3 pr-4">{cell}</td>)}</tr>)}</tbody></table></div>; }
