import { authorizeAdminApi } from "@/lib/admin/auth";
import { Prisma } from "@/generated/prisma/client";
import { writeAuditLog } from "@/lib/admin/audit";
import { apiError, apiSuccess, handleApiError } from "@/lib/api-response";
import { logSellerActivity } from "@/lib/seller/activity";
import { payoutProcessSchema } from "@/lib/seller/schemas";
import { prisma } from "@/lib/prisma";

const allowed = { REQUESTED: ["PROCESSING", "CANCELLED"], PROCESSING: ["PAID", "FAILED"], FAILED: ["PROCESSING", "CANCELLED"], PAID: [], CANCELLED: [] } as const;
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const auth = await authorizeAdminApi("payouts:write"); if (!auth.user) return auth.response; const id = (await params).id; const data = payoutProcessSchema.parse(await request.json()); const current = await prisma.payout.findUnique({ where: { id } }); if (!current) return apiError("NOT_FOUND", "Payout tidak ditemukan.", 404); if (!(allowed[current.status] as readonly string[]).includes(data.status)) return apiError("INVALID_PAYOUT_TRANSITION", "Perubahan status payout tidak valid.", 409); if (["FAILED", "CANCELLED"].includes(data.status) && !data.reason) return apiError("REASON_REQUIRED", "Alasan wajib diisi.", 422); if (data.status === "PAID" && !data.providerRef) return apiError("PROVIDER_REF_REQUIRED", "Referensi transfer wajib diisi.", 422); const payout = await prisma.$transaction(async (tx) => { const updated = await tx.payout.update({ where: { id }, data: { status: data.status, providerRef: data.providerRef || current.providerRef, failureReason: data.status === "FAILED" ? data.reason : null, processedAt: data.status === "PROCESSING" ? new Date() : current.processedAt, paidAt: data.status === "PAID" ? new Date() : current.paidAt } }); await logSellerActivity(tx, { sellerId: current.sellerId, actorUserId: auth.user.id, action: `PAYOUT_${data.status}`, entityType: "Payout", entityId: id, moneyBefore: data.status === "PAID" ? current.amount : undefined, moneyAfter: data.status === "PAID" ? new Prisma.Decimal(0) : undefined, metadata: { from: current.status, providerRef: data.providerRef, reason: data.reason } }); await writeAuditLog(tx, { userId: auth.user.id, action: `SELLER_PAYOUT_${data.status}`, entityType: "Payout", entityId: id, metadata: { amount: current.amount, reason: data.reason }, request }); return updated; }); return apiSuccess({ id, status: payout.status }); } catch (error) { return handleApiError(error); } }
