import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { AdminDashboard } from "@/components/admin/admin-dashboard";
import { AdminObjectTable } from "@/components/admin/admin-object-table";
import { AdminPagination } from "@/components/admin/admin-pagination";
import { CustomerAccessControl } from "@/components/admin/customer-access-control";
import { EntityManager, type EntityField } from "@/components/admin/entity-manager";
import { ProductForm } from "@/components/admin/product-form";
import { RecordEditor, type RecordField } from "@/components/admin/record-editor";
import { SectionVisibility } from "@/components/admin/section-visibility";
import { SellerReviewControl } from "@/components/admin/seller-review-control";
import { Button } from "@/components/ui/button";
import { authenticatedBackendApi } from "@/lib/authenticated-backend-api";
import { requireAdmin } from "@/lib/admin/auth";
import type { AdminPermission } from "@/lib/admin/permissions";

type Search = Promise<Record<string, string | string[] | undefined>>;
type Value = null | string | number | boolean | Date | Value[] | { [key: string]: Value };
type Obj = { [key: string]: Value };
const viewNames: Record<string, string> = { "": "dashboard", products: "products", orders: "orders", customers: "customers", users: "customers", categories: "categories", brands: "brands", vouchers: "vouchers", content: "content", testimonials: "content", inventory: "inventory", shipments: "shipments", "audit-logs": "audit", reports: "reports", search: "search", sellers: "sellers", "sellers/activity": "seller-activity", "sellers/payouts": "payouts", "sellers/submissions": "submissions" };

export default async function RemoteAdminPage({ params, searchParams }: { params: Promise<{ segments?: string[] }>; searchParams: Search }) {
  const segments = (await params).segments ?? []; const path = segments.join("/"); const admin = await requireAdmin(permissionForPath(path)); const query = new URLSearchParams();
  for (const [key, value] of Object.entries(await searchParams)) if (typeof value === "string") query.set(key, value);
  const detail = detailEndpoint(segments); const view = viewNames[path]; const isNewProduct = path === "products/new"; if (!detail && !view && !isNewProduct) notFound();
  const endpoint = detail ?? `/admin/views/${view ?? "options"}${query.size ? `?${query}` : ""}`;
  const data = (await authenticatedBackendApi<Value>(endpoint, { cache: "no-store" })).data;
  const options = isNewProduct || segments[0] === "products" && segments[1] ? (await authenticatedBackendApi<Obj>("/admin/views/options", { cache: "no-store" })).data : null;
  const title = path ? path.split("/").map(titleCase).join(" · ") : "Commerce overview";
  const action = path === "products" && admin.role === "ADMIN" ? <Button asChild><Link href="/admin/products/new">Add product</Link></Button> : path === "sellers" ? <div className="flex flex-wrap gap-2"><Button variant="outline" asChild><Link href="/admin/sellers/submissions">Submissions</Link></Button><Button variant="outline" asChild><Link href="/admin/sellers/payouts">Payouts</Link></Button><Button variant="outline" asChild><Link href="/admin/sellers/activity">Activity</Link></Button></div> : undefined;
  return <div><AdminPageHeader title={title} description="Data is managed through the backend API and stored in PostgreSQL." action={action} />
    {isNewProduct ? <ProductForm categories={optionList(options, "categories")} brands={optionList(options, "brands")} /> : <ManagedContent path={path} data={data} options={options} isAdmin={admin.role === "ADMIN"} />}
  </div>;
}

function ManagedContent({ path, data, options, isAdmin }: { path: string; data: Value; options: Obj | null; isAdmin: boolean }) {
  const object = asObject(data);
  if (path === "" && object) return <AdminDashboard data={object as unknown as Parameters<typeof AdminDashboard>[0]["data"]} />;
  if (path.startsWith("products/") && object && options) return <ProductForm productId={String(object.id)} categories={optionList(options, "categories")} brands={optionList(options, "brands")} initial={productValues(object)} />;
  if ((path.startsWith("customers/") || path.startsWith("users/")) && object) return <div className="grid gap-6 xl:grid-cols-[1fr_22rem]"><ApiData value={data} /><aside className="h-fit border border-[#ded9cf] bg-[#faf8f3] p-5"><h2 className="mb-5 font-serif text-2xl">Account access</h2>{isAdmin ? <CustomerAccessControl id={String(object.id)} initialActive={Boolean(object.isActive)} initialRole={String(object.role)} initialVerified={Boolean(object.emailVerified)} /> : <p className="text-sm">Only ADMIN can change access.</p>}</aside></div>;
  if (path.startsWith("orders/") && object && isAdmin) return <div className="space-y-5"><RecordEditor title={String(object.orderNumber)} endpoint={`/admin/orders/${object.id}`} fields={[select("status", "Order status", ["PENDING_PAYMENT", "PAID", "PROCESSING", "SHIPPED", "DELIVERED", "CANCELLED", "REFUNDED"]), select("paymentStatus", "Payment status", ["PENDING", "AUTHORIZED", "PAID", "FAILED", "EXPIRED", "CANCELLED", "REFUNDED", "PARTIALLY_REFUNDED"]), { name: "trackingNumber", label: "Tracking number" }]} initial={{ status: String(object.status), paymentStatus: String(object.paymentStatus), trackingNumber: object.trackingNumber ? String(object.trackingNumber) : "" }} /><ApiData value={data} /></div>;
  if (/^sellers\/(?!activity$|payouts$|submissions$)[^/]+$/.test(path) && object) return <div className="grid gap-6 xl:grid-cols-[1fr_22rem]"><ApiData value={data} /><aside className="h-fit border border-[#ded9cf] bg-[#faf8f3] p-5"><h2 className="mb-5 font-serif text-2xl">Seller review</h2>{isAdmin ? <SellerReviewControl id={String(object.id)} status={String(object.status)} rate={Number(object.commissionRate)} /> : <p className="text-sm">Only ADMIN can review sellers.</p>}</aside></div>;
  if (["categories", "brands", "vouchers", "content", "testimonials"].includes(path) && object) { const pagination = paginationFrom(object); return <div><EntityContent path={path} data={object} isAdmin={isAdmin} />{pagination ? <div className="mt-4 overflow-hidden rounded-lg border border-[#ded8cd]"><AdminPagination pagination={pagination} /></div> : null}</div>; }
  if ((path === "inventory" || path === "shipments") && object) return <EditableRecords resource={path} data={object} isAdmin={isAdmin} />;
  return <ApiData value={data} basePath={["products", "orders", "customers", "sellers"].includes(path) ? `/admin/${path}` : undefined} />;
}

const categoryFields: EntityField[] = [{ name: "name", label: "Name" }, { name: "slug", label: "Slug" }, { name: "description", label: "Description", type: "textarea" }, { name: "sortOrder", label: "Sort order", type: "number" }, { name: "isActive", label: "Active", type: "checkbox" }];
const brandFields: EntityField[] = [{ name: "name", label: "Name" }, { name: "slug", label: "Slug" }, { name: "description", label: "Description", type: "textarea" }, { name: "logoUrl", label: "Logo URL" }, { name: "isFeatured", label: "Featured", type: "checkbox" }, { name: "isActive", label: "Active", type: "checkbox" }];
const voucherFields: EntityField[] = [{ name: "code", label: "Code" }, { name: "name", label: "Name" }, { name: "type", label: "Type", type: "select", options: ["PERCENTAGE", "FIXED_AMOUNT", "FREE_SHIPPING"].map((value) => ({ value, label: value })) }, { name: "value", label: "Value", type: "number" }, { name: "minSpend", label: "Minimum spend", type: "number" }, { name: "maxDiscount", label: "Maximum discount", type: "number" }, { name: "usageLimit", label: "Usage limit", type: "number" }, { name: "usagePerUser", label: "Usage per user", type: "number" }, { name: "startsAt", label: "Starts", type: "datetime-local" }, { name: "endsAt", label: "Ends", type: "datetime-local" }, { name: "description", label: "Description", type: "textarea" }, { name: "isActive", label: "Active", type: "checkbox" }];
const bannerFields: EntityField[] = [{ name: "name", label: "Name" }, { name: "placement", label: "Placement" }, { name: "title", label: "Title" }, { name: "imageUrl", label: "Image URL" }, { name: "imageAlt", label: "Image alt" }, { name: "body", label: "Body", type: "textarea" }, { name: "sortOrder", label: "Sort order", type: "number" }, { name: "isActive", label: "Active", type: "checkbox" }];
const testimonialFields: EntityField[] = [{ name: "name", label: "Customer name" }, { name: "location", label: "Location" }, { name: "quote", label: "Testimonial", type: "textarea" }, { name: "rating", label: "Rating", type: "number" }, { name: "sortOrder", label: "Sort order", type: "number" }, { name: "isActive", label: "Active", type: "checkbox" }];

function EntityContent({ path, data, isAdmin }: { path: string; data: Obj; isAdmin: boolean }) {
  const entity = path === "testimonials" ? "testimonials" : path;
  // Voucher defaults are relative to this server-rendered request.
  // eslint-disable-next-line react-hooks/purity
  if (["categories", "brands", "vouchers"].includes(entity)) { const items = asArray(data.items); const fields = entity === "categories" ? categoryFields : entity === "brands" ? brandFields : voucherFields; const defaults = entity === "categories" ? { name: "", slug: "", description: "", parentId: null, imageUrl: "", sortOrder: 0, isActive: true } : entity === "brands" ? { name: "", slug: "", description: "", logoUrl: "", isFeatured: false, isActive: true } : { code: "", name: "", type: "PERCENTAGE", value: 10, minSpend: 0, maxDiscount: 0, usageLimit: 100, usagePerUser: 1, startsAt: new Date(), endsAt: new Date(Date.now() + 2_592_000_000), description: "", isActive: true }; return <ResourceSection title={titleCase(entity)} action={isAdmin ? <EntityManager entity={entity as "categories" | "brands" | "vouchers"} fields={fields} defaults={defaults} /> : null} items={items} renderAction={(item) => isAdmin ? <EntityManager entity={entity as "categories" | "brands" | "vouchers"} fields={fields} defaults={defaults} initial={entityInitial(item)} /> : null} />; }
  const sections = asArray(data.sections); const bannerData = asObject(data.banners); const testimonialData = asObject(data.testimonials); const banners = asArray(bannerData?.items ?? data.banners); const testimonials = asArray(testimonialData?.items ?? data.testimonials); if (path === "testimonials") return <ResourceSection title="Testimonials" action={isAdmin ? <EntityManager entity="testimonials" fields={testimonialFields} defaults={{ name: "", location: "", quote: "", rating: 5, sortOrder: 0, isActive: true }} /> : null} items={testimonials} pagination={testimonialData ? paginationFrom(testimonialData) : undefined} pageParam="testimonialPage" renderAction={(item) => isAdmin ? <EntityManager entity="testimonials" fields={testimonialFields} defaults={{}} initial={entityInitial(item)} /> : null} />;
  return <div className="space-y-6">{isAdmin && <SectionVisibility initial={sections.map((item) => ({ id: String(item.id), key: String(item.key), title: String(item.title), isVisible: Boolean(item.isVisible), sortOrder: Number(item.sortOrder) }))} />}<ResourceSection title="Banners" action={isAdmin ? <EntityManager entity="banners" fields={bannerFields} defaults={{ name: "", placement: "HOME_PROMO", title: "", body: "", imageUrl: "", imageAlt: "", sortOrder: 0, isActive: true }} /> : null} items={banners} pagination={bannerData ? paginationFrom(bannerData) : undefined} pageParam="bannerPage" renderAction={(item) => isAdmin ? <EntityManager entity="banners" fields={bannerFields} defaults={{}} initial={entityInitial(item)} /> : null} /><ResourceSection title="Testimonials" action={isAdmin ? <EntityManager entity="testimonials" fields={testimonialFields} defaults={{ name: "", location: "", quote: "", rating: 5, sortOrder: 0, isActive: true }} /> : null} items={testimonials} pagination={testimonialData ? paginationFrom(testimonialData) : undefined} pageParam="testimonialPage" renderAction={(item) => isAdmin ? <EntityManager entity="testimonials" fields={testimonialFields} defaults={{}} initial={entityInitial(item)} /> : null} /></div>;
}

function EditableRecords({ resource, data, isAdmin }: { resource: string; data: Obj; isAdmin: boolean }) { const items = asArray(data.items); const shipmentFields: RecordField[] = [{ name: "courier", label: "Courier" }, { name: "provider", label: "Provider" }, { name: "service", label: "Service" }, { name: "providerRef", label: "Provider ref" }, { name: "trackingNumber", label: "Tracking number" }, select("status", "Status", ["PENDING", "READY", "IN_TRANSIT", "DELIVERED", "RETURNED", "FAILED"])]; const inventoryFields: RecordField[] = [{ name: "quantity", label: "Physical quantity", type: "number" }, { name: "lowStockAt", label: "Low-stock threshold", type: "number" }]; const columns = resource === "inventory" ? ["productName", "sku", "variantName", "color", "size", "quantity", "reserved", "available", "lowStockAt", "status"] : ["order", "courier", "service", "trackingNumber", "status", "updatedAt"]; return <section><div className="mb-4"><h2 className="text-base font-semibold">{titleCase(resource)}</h2><p className="mt-1 text-xs text-muted-foreground">{resource === "inventory" ? "Physical, reserved, and available stock per product variant." : "Courier and tracking status for every order shipment."}</p></div><AdminObjectTable items={items} pagination={paginationFrom(data)} columns={columns} renderAction={(item) => isAdmin ? <RecordEditor title={String(item.sku ?? item.id)} endpoint={`/admin/${resource}/${item.id}`} fields={resource === "shipments" ? shipmentFields : inventoryFields} initial={resource === "shipments" ? pick(item as Obj, ["courier", "provider", "service", "providerRef", "trackingNumber", "status"]) : pick(item as Obj, ["quantity", "lowStockAt"])} /> : null} /></section>; }
function ResourceSection({ title, items, action, renderAction, pagination, pageParam }: { title: string; items: Obj[]; action?: React.ReactNode; renderAction: (item: Obj) => React.ReactNode; pagination?: ReturnType<typeof paginationFrom>; pageParam?: string }) { return <section><div className="mb-4 flex items-center justify-between"><h2 className="text-base font-semibold">{title}</h2>{action}</div><AdminObjectTable items={items} pagination={pagination} pageParam={pageParam} renderAction={renderAction as (item: Record<string, unknown>) => React.ReactNode} /></section>; }

function detailEndpoint(segments: string[]) { if (segments[0] === "products" && segments[1] && segments[1] !== "new") return `/admin/details/products/${encodeURIComponent(segments[1])}`; if (segments[0] === "orders" && segments[1]) return `/admin/details/orders/${encodeURIComponent(segments[1])}`; if (["customers", "users"].includes(segments[0]) && segments[1]) return `/admin/details/customers/${encodeURIComponent(segments[1])}`; if (segments[0] === "sellers" && segments[1] === "submissions" && segments[2]) return `/admin/details/submissions/${encodeURIComponent(segments[2])}`; if (segments[0] === "sellers" && segments[1] && !["activity", "payouts", "submissions"].includes(segments[1])) return `/admin/details/sellers/${encodeURIComponent(segments[1])}`; return null; }
function ApiData({ value, compact = false, basePath }: { value: Value; compact?: boolean; basePath?: string }) {
  if (value == null) return <span>—</span>;
  if (Array.isArray(value)) { const rows = value.map(asObject).filter((item): item is Obj => Boolean(item)); return rows.length === value.length ? <AdminObjectTable items={rows} basePath={basePath} /> : value.length ? <div className="grid gap-2">{value.map((item, index) => <ApiData key={index} value={item} />)}</div> : <p className="text-sm text-muted-foreground">No data.</p>; }
  if (!asObject(value)) return <span>{String(value)}</span>;
  const object = asObject(value)!; const primary = asArray(object.items); if (Array.isArray(object.items)) return <AdminObjectTable items={primary} basePath={basePath} pagination={paginationFrom(object)} />;
  const scalarEntries = Object.entries(object).filter(([, item]) => !asObject(item) && !Array.isArray(item)); const nestedEntries = Object.entries(object).filter(([, item]) => asObject(item) || Array.isArray(item));
  return <article className={compact ? "" : "border border-[#ded9cf] bg-[#faf8f3] p-5"}><dl className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{scalarEntries.slice(0, compact ? 8 : 30).map(([key, item]) => <div key={key}><dt className="text-[0.625rem] font-semibold tracking-wider text-muted-foreground uppercase">{titleCase(key)}</dt><dd className="mt-1 break-words text-sm">{item == null ? "—" : String(item)}</dd></div>)}</dl>{basePath && object.id ? <Link className="mt-4 inline-block text-xs font-semibold underline" href={`${basePath}/${object.id}`}>Manage</Link> : null}{!compact && nestedEntries.map(([key, item]) => <section key={key} className="mt-6 border-t border-[#ded9cf] pt-5"><h2 className="mb-3 font-serif text-2xl">{titleCase(key)}</h2><ApiData value={item} basePath={adminBasePath(key)} /></section>)}</article>;
}
function adminBasePath(key: string) { return ["products", "orders", "customers", "sellers"].includes(key) ? `/admin/${key}` : undefined; }
function permissionForPath(path: string): AdminPermission { if (path.startsWith("products") || path === "inventory") return "products:read"; if (path.startsWith("categories")) return "categories:read"; if (path.startsWith("brands")) return "brands:read"; if (path.startsWith("orders") || path === "shipments") return "orders:read"; if (path.startsWith("customers") || path.startsWith("users")) return "customers:read"; if (path.startsWith("vouchers")) return "vouchers:read"; if (path === "content" || path === "testimonials") return "content:read"; if (path === "reports") return "reports:read"; if (path === "audit-logs") return "audit:read"; if (path === "sellers/payouts") return "payouts:read"; if (path.startsWith("sellers")) return "sellers:read"; return "dashboard:read"; }
function asObject(value: Value | undefined): Obj | null { return Boolean(value) && typeof value === "object" && !Array.isArray(value) && !(value instanceof Date) ? value as Obj : null; }
function asArray(value: Value | undefined): Obj[] { return Array.isArray(value) ? value.map(asObject).filter((item): item is Obj => Boolean(item)) : []; }
function optionList(options: Obj | null, key: string) { return asArray(options?.[key]).map((item) => ({ id: String(item.id), name: String(item.name) })); }
function entityInitial(item: Obj) { return Object.fromEntries(Object.entries(item).filter(([, value]) => !Array.isArray(value) && !asObject(value)).map(([key, value]) => [key, value == null ? null : value])) as Record<string, string | number | boolean | null> & { id: string }; }
function pick(item: Obj, keys: string[]) { return Object.fromEntries(keys.map((key) => [key, item[key] == null ? null : item[key]])) as Record<string, string | number | boolean | null>; }
function paginationFrom(value: Obj) { const total = Number(value.total); const page = Number(value.page); const pageSize = Number(value.pageSize); if (![total, page, pageSize].every(Number.isFinite)) return undefined; return { total, page, pageSize, totalPages: Number(value.totalPages) || Math.max(1, Math.ceil(total / pageSize)) }; }
function select(name: string, label: string, options: string[]): RecordField { return { name, label, type: "select", options }; }
function productValues(item: Obj) { return { name: String(item.name), slug: String(item.slug), baseSku: String(item.baseSku), categoryId: String(item.categoryId), brandId: String(item.brandId), description: String(item.description), shortDescription: item.shortDescription ? String(item.shortDescription) : "", condition: String(item.condition) as "NEW" | "PRELOVED", conditionLabel: item.conditionLabel ? String(item.conditionLabel) : "", completeness: item.completeness ? String(item.completeness) : "", flawNotes: item.flawNotes ? String(item.flawNotes) : "", authenticationStatus: item.authenticationStatus ? String(item.authenticationStatus) : "", price: Number(item.price), compareAtPrice: item.compareAtPrice == null ? null : Number(item.compareAtPrice), costPrice: item.costPrice == null ? null : Number(item.costPrice), status: String(item.status) as "DRAFT" | "ACTIVE" | "ARCHIVED", isFeatured: Boolean(item.isFeatured), isNewArrival: Boolean(item.isNewArrival), weightGrams: item.weightGrams == null ? null : Number(item.weightGrams), images: asArray(item.images).map((image) => ({ id: String(image.id), url: String(image.url), alt: String(image.alt), width: Number(image.width), height: Number(image.height), isPrimary: Boolean(image.isPrimary) })), variants: asArray(item.variants).map((variant) => { const inventory = asObject(variant.inventory); return { id: String(variant.id), sku: String(variant.sku), name: String(variant.name), color: variant.color ? String(variant.color) : "", colorHex: variant.colorHex ? String(variant.colorHex) : "", size: variant.size ? String(variant.size) : "", price: variant.price == null ? null : Number(variant.price), compareAtPrice: variant.compareAtPrice == null ? null : Number(variant.compareAtPrice), weightInGrams: Number(variant.weightInGrams ?? 1000), stock: Number(inventory?.quantity ?? 0), lowStockAt: Number(inventory?.lowStockAt ?? 2), isActive: Boolean(variant.isActive) }; }) }; }
function titleCase(value: string) { return value.replaceAll("-", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
