import { AdminDataTable } from "@/components/admin/admin-data-table";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { EntityManager, type EntityField } from "@/components/admin/entity-manager";
import { Badge } from "@/components/ui/badge";
import { requireAdmin } from "@/lib/admin/auth";
import { ADMIN_PAGE_SIZE, parseAdminQuery, type AdminSearchParams } from "@/lib/admin/query";
import { prisma } from "@/lib/prisma";

export default async function CategoriesPage({ searchParams }: { searchParams: AdminSearchParams }) { const user = await requireAdmin("categories:read"); const query = await parseAdminQuery(searchParams); const where = { deletedAt: null, ...(query.q ? { name: { contains: query.q, mode: "insensitive" as const } } : {}), ...(query.status ? { isActive: query.status === "active" } : {}) }; const [rows, total, options] = await Promise.all([prisma.category.findMany({ where, include: { parent: true, _count: { select: { products: true } } }, orderBy: [{ sortOrder: "asc" }, { name: "asc" }], skip: (query.page - 1) * ADMIN_PAGE_SIZE, take: ADMIN_PAGE_SIZE }), prisma.category.count({ where }), prisma.category.findMany({ where: { deletedAt: null }, select: { id: true, name: true }, orderBy: { name: "asc" } })]); const fields: EntityField[] = [{ name: "name", label: "Name" }, { name: "slug", label: "Slug" }, { name: "parentId", label: "Parent category", type: "select", options: options.map((item) => ({ value: item.id, label: item.name })) }, { name: "imageUrl", label: "Image URL" }, { name: "description", label: "Description", type: "textarea" }, { name: "sortOrder", label: "Sort order", type: "number" }, { name: "isActive", label: "Active", type: "checkbox" }]; const defaults = { name: "", slug: "", parentId: null, imageUrl: "", description: "", sortOrder: 0, isActive: true }; return <div><AdminPageHeader title="Categories" description="Atur hierarchy, slug, urutan, dan status kategori." breadcrumbs={[{ label: "Categories" }]} action={user.role === "ADMIN" ? <EntityManager entity="categories" fields={fields} defaults={defaults} /> : null} /><AdminDataTable columns={[{ key: "name", label: "Category" }, { key: "parent", label: "Parent" }, { key: "products", label: "Products" }, { key: "status", label: "Status" }, { key: "action", label: "" }]} rows={rows.map((row) => ({ id: row.id, cells: { name: <div><p className="font-semibold">{row.name}</p><p className="text-xs text-muted-foreground">/{row.slug}</p></div>, parent: row.parent?.name ?? "—", products: row._count.products, status: <Badge variant={row.isActive ? "secondary" : "outline"}>{row.isActive ? "Active" : "Inactive"}</Badge>, action: user.role === "ADMIN" ? <EntityManager entity="categories" fields={fields} defaults={defaults} initial={{ id: row.id, name: row.name, slug: row.slug, parentId: row.parentId, imageUrl: row.imageUrl ?? "", description: row.description ?? "", sortOrder: row.sortOrder, isActive: row.isActive }} /> : null } }))} page={query.page} total={total} totalPages={Math.max(1, Math.ceil(total / ADMIN_PAGE_SIZE))} bulkEndpoint={user.role === "ADMIN" ? "/api/admin/entities/categories" : undefined} filters={[{ value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }]} /></div>; }
