import { CurrencyCircleDollarIcon, PackageIcon, ReceiptIcon, UsersIcon, WarningIcon } from "@phosphor-icons/react/dist/ssr";
import { AdminObjectTable } from "@/components/admin/admin-object-table";
import { formatIDR } from "@/lib/formatters";

type Sale = { grandTotal: number | string; placedAt: Date | string };
type DashboardData = { sales?: Sale[]; totalOrders?: number; totalCustomers?: number; pendingOrders?: number; recentOrders?: Record<string, unknown>[]; lowStock?: Record<string, unknown>[]; orderItems?: Array<{ productName?: string; quantity?: number; lineTotal?: number | string }> };

export function AdminDashboard({ data }: { data: DashboardData }) {
  const sales = data.sales ?? []; const revenue = sales.reduce((sum, sale) => sum + Number(sale.grandTotal), 0); const daily = salesByDay(sales); const max = Math.max(...daily.map((item) => item.value), 1); const topProducts = summarizeProducts(data.orderItems ?? []);
  const cards = [
    { label: "Revenue", value: formatIDR(revenue), detail: "Paid orders", icon: CurrencyCircleDollarIcon },
    { label: "Orders", value: String(data.totalOrders ?? 0), detail: `${data.pendingOrders ?? 0} need attention`, icon: ReceiptIcon },
    { label: "Customers", value: String(data.totalCustomers ?? 0), detail: "Registered accounts", icon: UsersIcon },
    { label: "Low stock", value: String(data.lowStock?.length ?? 0), detail: "Variants below threshold", icon: PackageIcon },
  ];
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, detail, icon: Icon }) => <section key={label} className="rounded-lg border border-[#ded8cd] bg-white p-5 shadow-[0_1px_2px_rgba(48,43,35,0.04)]"><div className="flex items-center justify-between"><p className="text-sm font-medium text-[#6f695f]">{label}</p><span className="grid size-9 place-items-center rounded-md bg-[#eee7da] text-[#766344]"><Icon className="size-5" aria-hidden /></span></div><p className="mt-4 text-2xl font-semibold tracking-tight text-[#292722]">{value}</p><p className="mt-1 text-xs text-[#837d73]">{detail}</p></section>)}</div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.55fr)_minmax(18rem,.75fr)]"><section className="rounded-lg border border-[#ded8cd] bg-white p-5"><div><h2 className="text-base font-semibold">Revenue overview</h2><p className="mt-1 text-xs text-muted-foreground">Paid revenue over the last seven active days.</p></div><div className="mt-8 flex h-56 items-end gap-3 border-b border-[#ded8cd] px-2">{daily.map((item) => <div key={item.label} className="flex h-full flex-1 flex-col justify-end gap-2"><div className="group relative min-h-1 rounded-t bg-[#a28a5b] transition-colors hover:bg-[#7d6944]" style={{ height: `${Math.max(3, item.value / max * 100)}%` }}><span className="absolute -top-7 left-1/2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-[#292722] px-2 py-1 text-[0.625rem] text-white group-hover:block">{formatIDR(item.value)}</span></div><span className="pb-2 text-center text-[0.625rem] text-muted-foreground">{item.label}</span></div>)}</div></section><section className="rounded-lg border border-[#ded8cd] bg-white p-5"><div className="flex items-center gap-2"><WarningIcon className="size-5 text-[#9b654e]" aria-hidden /><h2 className="text-base font-semibold">Attention</h2></div><div className="mt-5 space-y-4"><Metric label="Pending orders" value={data.pendingOrders ?? 0} /><Metric label="Low-stock variants" value={data.lowStock?.length ?? 0} /><Metric label="Top products tracked" value={topProducts.length} /></div></section></div>
    <section><div className="mb-3"><h2 className="text-base font-semibold">Recent orders</h2><p className="mt-1 text-xs text-muted-foreground">Latest commerce activity.</p></div><AdminObjectTable items={data.recentOrders ?? []} basePath="/admin/orders" columns={["orderNumber", "customerName", "status", "grandTotal", "placedAt"]} /></section>
    <div className="grid gap-6 xl:grid-cols-2"><section><div className="mb-3"><h2 className="text-base font-semibold">Low stock</h2></div><AdminObjectTable items={data.lowStock ?? []} columns={["variant", "quantity", "reserved", "lowStockAt", "updatedAt"]} /></section><section><div className="mb-3"><h2 className="text-base font-semibold">Top products</h2></div><AdminObjectTable items={topProducts} columns={["productName", "quantity", "revenue"]} /></section></div>
  </div>;
}

function Metric({ label, value }: { label: string; value: number }) { return <div className="flex items-center justify-between border-b border-[#ece7de] pb-4 last:border-0"><span className="text-sm text-[#6f695f]">{label}</span><span className="rounded-md bg-[#f1ece2] px-2.5 py-1 text-sm font-semibold tabular-nums">{value}</span></div>; }
function salesByDay(sales: Sale[]) { const map = new Map<string, number>(); for (const sale of sales) { const date = new Date(sale.placedAt); const key = new Intl.DateTimeFormat("id-ID", { day: "2-digit", month: "short" }).format(date); map.set(key, (map.get(key) ?? 0) + Number(sale.grandTotal)); } const values = [...map].slice(-7).map(([label, value]) => ({ label, value })); return values.length ? values : Array.from({ length: 7 }, (_, index) => ({ label: `D${index + 1}`, value: 0 })); }
function summarizeProducts(items: NonNullable<DashboardData["orderItems"]>) { const map = new Map<string, { productName: string; quantity: number; revenue: number }>(); for (const item of items) { const name = item.productName ?? "Unknown"; const row = map.get(name) ?? { productName: name, quantity: 0, revenue: 0 }; row.quantity += item.quantity ?? 0; row.revenue += Number(item.lineTotal ?? 0); map.set(name, row); } return [...map.values()].sort((a, b) => b.revenue - a.revenue).slice(0, 6); }
