"use client";

import { apiFetch } from "@/lib/api-client";
/* eslint-disable react-hooks/incompatible-library -- React Hook Form exposes watch(), which React Compiler intentionally skips. */

import { useEffect, useState } from "react";
import { useFieldArray, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { FloppyDiskIcon, PlusIcon, SpinnerGapIcon, TrashIcon } from "@phosphor-icons/react";
import { toast } from "sonner";
import type { z } from "zod";

import { productAdminSchema } from "@/lib/admin/schemas";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";

type Values = z.input<typeof productAdminSchema>;
type Option = { id: string; name: string };

export function ProductForm({ productId, initial, categories, brands }: { productId?: string; initial?: Values; categories: Option[]; brands: Option[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false);
  const form = useForm<Values>({ resolver: zodResolver(productAdminSchema), defaultValues: initial ?? { name: "", slug: "", baseSku: "", categoryId: categories[0]?.id ?? "", brandId: brands[0]?.id ?? "", description: "", shortDescription: "", condition: "NEW", conditionLabel: "", completeness: "", flawNotes: "", authenticationStatus: "", price: 0, compareAtPrice: null, costPrice: null, status: "DRAFT", isFeatured: false, isNewArrival: false, weightGrams: 1000, images: [{ url: "", alt: "", width: 1200, height: 1500, isPrimary: true }], variants: [{ sku: "", name: "Default", color: "", colorHex: "", size: "One Size", price: null, compareAtPrice: null, stock: 0, lowStockAt: 2, isActive: true }] } });
  const images = useFieldArray({ control: form.control, name: "images" }); const variants = useFieldArray({ control: form.control, name: "variants" });
  useEffect(() => { const warning = (event: BeforeUnloadEvent) => { if (form.formState.isDirty) event.preventDefault(); }; window.addEventListener("beforeunload", warning); return () => window.removeEventListener("beforeunload", warning); }, [form.formState.isDirty]);
  async function submit(values: Values) { setBusy(true); try { const response = await apiFetch(productId ? `/api/admin/products/${productId}` : "/api/admin/products", { method: productId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const result = await response.json() as { success?: boolean; data?: { id: string }; error?: { message?: string } }; if (!result.success) throw new Error(result.error?.message); toast.success(productId ? "Produk diperbarui." : "Produk dibuat."); form.reset(values); router.push("/admin/products"); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Produk gagal disimpan."); } finally { setBusy(false); } }
  return <Form {...form}><form onSubmit={form.handleSubmit(submit)} className="space-y-6"><section className="grid gap-5 border border-[#ded9cf] bg-[#faf8f3] p-5 sm:grid-cols-2 sm:p-6"><h2 className="font-serif text-2xl sm:col-span-2">Core information</h2><TextField form={form} name="name" label="Product name" /><TextField form={form} name="slug" label="Slug" /><TextField form={form} name="baseSku" label="Base SKU" /><SelectField form={form} name="status" label="Status" options={[{ id: "DRAFT", name: "Draft" }, { id: "ACTIVE", name: "Published" }, { id: "ARCHIVED", name: "Archived" }]} /><SelectField form={form} name="categoryId" label="Category" options={categories} /><SelectField form={form} name="brandId" label="Brand" options={brands} /><SelectField form={form} name="condition" label="Condition" options={[{ id: "NEW", name: "New" }, { id: "PRELOVED", name: "Preloved" }]} /><TextField form={form} name="authenticationStatus" label="Authenticity status" /><TextField form={form} name="shortDescription" label="Short description" className="sm:col-span-2" /><TextAreaField form={form} name="description" label="Description" /><TextAreaField form={form} name="flawNotes" label="Preloved flaw notes" /><TextField form={form} name="price" label="Price (IDR)" type="number" /><TextField form={form} name="compareAtPrice" label="Compare-at price" type="number" /><TextField form={form} name="costPrice" label="Cost price" type="number" /><TextField form={form} name="weightGrams" label="Weight (grams)" type="number" /><BooleanField form={form} name="isFeatured" label="Featured product" /><BooleanField form={form} name="isNewArrival" label="New arrival" /></section>
  <section className="border border-[#ded9cf] bg-[#faf8f3] p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-serif text-2xl">Images</h2><p className="mt-1 text-xs text-muted-foreground">URL aman dapat diganti upload service kemudian.</p></div><Button type="button" variant="outline" onClick={() => images.append({ url: "", alt: "", width: 1200, height: 1500, isPrimary: false })}><PlusIcon aria-hidden /> Add image</Button></div><div className="mt-5 grid gap-5 md:grid-cols-2">{images.fields.map((field, index) => { const url = safePreviewUrl(String(form.watch(`images.${index}.url`) ?? "")); return <div key={field.id} className="grid gap-4 border border-[#ded9cf] p-4 sm:grid-cols-[7rem_1fr]"><div className="aspect-[4/5] bg-[#ebe6dc] bg-cover bg-center" style={url ? { backgroundImage: `url("${url.replaceAll('"', '%22')}")` } : undefined} aria-label="Image preview" /><div className="space-y-3"><TextField form={form} name={`images.${index}.url`} label="Image URL" /><TextField form={form} name={`images.${index}.alt`} label="Alt text" /><BooleanField form={form} name={`images.${index}.isPrimary`} label="Primary" /><Button type="button" size="sm" variant="destructive" disabled={images.fields.length === 1} onClick={() => images.remove(index)}><TrashIcon aria-hidden /> Remove</Button></div></div>; })}</div></section>
  <section className="border border-[#ded9cf] bg-[#faf8f3] p-5 sm:p-6"><div className="flex items-center justify-between"><h2 className="font-serif text-2xl">Variants & stock</h2><Button type="button" variant="outline" onClick={() => variants.append({ sku: "", name: "", color: "", colorHex: "", size: "", price: null, compareAtPrice: null, stock: 0, lowStockAt: 2, isActive: true })}><PlusIcon aria-hidden /> Add variant</Button></div><div className="mt-5 space-y-4">{variants.fields.map((field, index) => <div key={field.id} className="grid gap-4 border border-[#ded9cf] p-4 sm:grid-cols-2 lg:grid-cols-4"><TextField form={form} name={`variants.${index}.sku`} label="SKU" /><TextField form={form} name={`variants.${index}.name`} label="Variant name" /><TextField form={form} name={`variants.${index}.color`} label="Color" /><TextField form={form} name={`variants.${index}.size`} label="Size" /><TextField form={form} name={`variants.${index}.price`} label="Override price" type="number" /><TextField form={form} name={`variants.${index}.stock`} label="Stock" type="number" /><TextField form={form} name={`variants.${index}.lowStockAt`} label="Low-stock threshold" type="number" /><div className="flex items-end gap-3"><BooleanField form={form} name={`variants.${index}.isActive`} label="Active" /><Button type="button" size="icon" variant="destructive" disabled={variants.fields.length === 1} onClick={() => variants.remove(index)} aria-label="Remove variant"><TrashIcon aria-hidden /></Button></div></div>)}</div></section>
  <div className="sticky bottom-4 flex justify-end"><Button size="lg" disabled={busy || !form.formState.isDirty}>{busy ? <SpinnerGapIcon className="animate-spin" aria-hidden /> : <FloppyDiskIcon aria-hidden />} Save product</Button></div></form></Form>;
}

type AnyForm = ReturnType<typeof useForm<Values>>;
function TextField({ form, name, label, type = "text", className }: { form: AnyForm; name: Parameters<AnyForm["register"]>[0]; label: string; type?: string; className?: string }) { return <FormField control={form.control} name={name} render={({ field }) => <FormItem className={className}><FormLabel>{label}</FormLabel><FormControl><Input {...field} value={(field.value as string | number | null | undefined) ?? ""} type={type} /></FormControl><FormMessage /></FormItem>} />; }
function TextAreaField({ form, name, label }: { form: AnyForm; name: Parameters<AnyForm["register"]>[0]; label: string }) { return <FormField control={form.control} name={name} render={({ field }) => <FormItem><FormLabel>{label}</FormLabel><FormControl><textarea {...field} value={(field.value as string | undefined) ?? ""} className="min-h-28 w-full rounded-md border border-input bg-white p-3 text-sm outline-none focus:ring-2 focus:ring-ring/30" /></FormControl><FormMessage /></FormItem>} />; }
function SelectField({ form, name, label, options }: { form: AnyForm; name: Parameters<AnyForm["register"]>[0]; label: string; options: Option[] }) { return <FormField control={form.control} name={name} render={({ field }) => <FormItem><FormLabel>{label}</FormLabel><FormControl><select {...field} value={String(field.value ?? "")} className="h-11 w-full rounded-md border border-input bg-white px-3 text-sm">{options.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></FormControl><FormMessage /></FormItem>} />; }
function BooleanField({ form, name, label }: { form: AnyForm; name: Parameters<AnyForm["register"]>[0]; label: string }) { return <FormField control={form.control} name={name} render={({ field }) => <FormItem className="flex items-center gap-3 pt-2"><FormControl><Checkbox checked={Boolean(field.value)} onCheckedChange={field.onChange} /></FormControl><FormLabel className="font-normal">{label}</FormLabel><FormDescription className="sr-only">Toggle {label}</FormDescription></FormItem>} />; }
function safePreviewUrl(value: string) { return value.startsWith("/") || /^https:\/\//i.test(value) ? value : ""; }
