"use client";

import { apiFetch } from "@/lib/api-client";
import { useState } from "react";
import { FloppyDiskIcon, SpinnerGapIcon } from "@phosphor-icons/react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";

type Section = { id: string; key: string; title: string; isVisible: boolean; sortOrder: number };
export function SectionVisibility({ initial }: { initial: Section[] }) { const [sections, setSections] = useState(initial); const [busy, setBusy] = useState(false); async function save() { setBusy(true); try { const response = await apiFetch("/api/admin/content/sections", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sections }) }); const result = await response.json() as { success?: boolean; error?: { message?: string } }; if (!result.success) throw new Error(result.error?.message); toast.success("Homepage visibility saved."); } catch (error) { toast.error(error instanceof Error ? error.message : "Gagal menyimpan."); } finally { setBusy(false); } } return <section className="border border-[#ded9cf] bg-[#faf8f3] p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-serif text-2xl">Section visibility</h2><p className="mt-1 text-xs text-muted-foreground">Urutan lebih kecil tampil lebih dahulu.</p></div><Button onClick={() => void save()} disabled={busy}>{busy ? <SpinnerGapIcon className="animate-spin" aria-hidden /> : <FloppyDiskIcon aria-hidden />}Save</Button></div><div className="mt-5 divide-y divide-[#ded9cf]">{sections.map((section, index) => <div key={section.id} className="flex items-center gap-4 py-3"><Checkbox checked={section.isVisible} onCheckedChange={(checked) => setSections((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, isVisible: Boolean(checked) } : item))} aria-label={`Tampilkan ${section.title}`} /><span className="flex-1 text-sm font-medium">{section.title}</span><input aria-label={`Urutan ${section.title}`} type="number" min={0} value={section.sortOrder} onChange={(event) => setSections((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, sortOrder: Number(event.target.value) } : item))} className="h-9 w-20 rounded-md border border-input bg-white px-2 text-sm" /></div>)}</div></section>; }
