import Link from "next/link";
import { ArrowRightIcon, ClockIcon, PackageIcon, WalletIcon } from "@phosphor-icons/react/dist/ssr";
import { SellerPageHeader } from "@/components/seller/seller-page-header";
import { Button } from "@/components/ui/button";
import { requireSeller } from "@/lib/seller/auth";
import { formatIDR } from "@/lib/formatters";
import { prisma } from "@/lib/prisma";
export default async function SellerOverview() { const { seller } = await requireSeller(); const [submissions, listed, sold, commissions] = await Promise.all([prisma.consignmentSubmission.count({ where: { sellerId: seller.id } }), prisma.consignmentSubmission.count({ where: { sellerId: seller.id, status: "LISTED" } }), prisma.consignmentSubmission.count({ where: { sellerId: seller.id, status: { in: ["SOLD", "COMPLETED"] } } }), prisma.commission.findMany({ where: { submission: { sellerId: seller.id, status: "COMPLETED" }, payoutItem: null, sellerNetAmount: { not: null } }, select: { sellerNetAmount: true } })]); const balance = commissions.reduce((sum, item) => sum + Number(item.sellerNetAmount), 0); return <div><SellerPageHeader title={`Welcome, ${seller.displayName}`} description="Pantau perjalanan produk dari review hingga dana tersedia." action={<Button asChild><Link href="/seller/submissions/new">New submission</Link></Button>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Submissions" value={String(submissions)} icon={PackageIcon} /><Metric label="Currently listed" value={String(listed)} icon={ClockIcon} /><Metric label="Sold" value={String(sold)} icon={ArrowRightIcon} /><Metric label="Available balance" value={formatIDR(balance)} icon={WalletIcon} /></div><section className="mt-6 border border-[#ddd5c7] bg-[#faf8f3] p-6"><h2 className="font-serif text-3xl">How consignment moves</h2><div className="mt-6 grid gap-4 md:grid-cols-4">{[["01", "Submit", "Detail dan foto diperiksa."], ["02", "Agree", "Terima estimasi kurasi."], ["03", "Sell", "Kami listing dan memenuhi order."], ["04", "Payout", "Dana tersedia setelah masa retur."]].map(([n, title, body]) => <div key={n} className="border-t border-[#aaa086] pt-4"><span className="text-xs text-[#9d895c]">{n}</span><h3 className="mt-4 font-serif text-2xl">{title}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{body}</p></div>)}</div></section></div>; }
function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: typeof PackageIcon }) { return <article className="border border-[#ddd5c7] bg-[#faf8f3] p-5"><Icon className="size-5 text-[#9d895c]" aria-hidden /><p className="mt-5 text-xs tracking-wider text-muted-foreground uppercase">{label}</p><p className="mt-2 font-serif text-3xl">{value}</p></article>; }
