import { authorizeAdminApi } from "@/lib/admin/auth";
import { writeAuditLog } from "@/lib/admin/audit";
import { productAdminSchema } from "@/lib/admin/schemas";
import { apiError, apiSuccess, handleApiError } from "@/lib/api-response";
import { prisma } from "@/lib/prisma";

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try { const auth = await authorizeAdminApi("products:write"); if (!auth.user) return auth.response; const id = (await params).id; const data = productAdminSchema.parse(await request.json()); const product = await prisma.$transaction(async (tx) => { const current = await tx.product.findUnique({ where: { id } }); if (!current) throw new Error("NOT_FOUND"); await tx.productImage.deleteMany({ where: { productId: id } }); const updated = await tx.product.update({ where: { id }, data: { name: data.name, slug: data.slug, baseSku: data.baseSku, categoryId: data.categoryId, brandId: data.brandId, description: data.description, shortDescription: data.shortDescription || null, condition: data.condition, conditionLabel: data.conditionLabel || null, completeness: data.completeness || null, flawNotes: data.flawNotes || null, authenticationStatus: data.authenticationStatus || null, price: data.price, compareAtPrice: data.compareAtPrice, costPrice: data.costPrice, status: data.status, publishedAt: data.status === "ACTIVE" ? current.publishedAt ?? new Date() : current.publishedAt, isFeatured: data.isFeatured, isNewArrival: data.isNewArrival, weightGrams: data.weightGrams, images: { create: data.images.map((image, index) => ({ url: image.url, alt: image.alt, width: image.width, height: image.height, isPrimary: image.isPrimary || index === 0, sortOrder: index })) } } }); for (const variant of data.variants) { if (variant.id) { await tx.productVariant.update({ where: { id: variant.id }, data: { sku: variant.sku, name: variant.name, color: variant.color || null, colorHex: variant.colorHex || null, size: variant.size || null, price: variant.price, compareAtPrice: variant.compareAtPrice, isActive: variant.isActive, inventory: { upsert: { create: { quantity: variant.stock, lowStockAt: variant.lowStockAt }, update: { quantity: variant.stock, lowStockAt: variant.lowStockAt, version: { increment: 1 } } } } } }); } else await tx.productVariant.create({ data: { productId: id, sku: variant.sku, name: variant.name, color: variant.color || null, colorHex: variant.colorHex || null, size: variant.size || null, price: variant.price, compareAtPrice: variant.compareAtPrice, isActive: variant.isActive, inventory: { create: { quantity: variant.stock, lowStockAt: variant.lowStockAt } } } }); } await writeAuditLog(tx, { userId: auth.user.id, action: "PRODUCT_UPDATED", entityType: "Product", entityId: id, metadata: { beforeStatus: current.status, afterStatus: updated.status }, request }); return updated; }); return apiSuccess({ id: product.id, slug: product.slug }); } catch (error) { if (error instanceof Error && error.message === "NOT_FOUND") return apiError("NOT_FOUND", "Produk tidak ditemukan.", 404); return handleApiError(error); }
}

export async function DELETE(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const auth = await authorizeAdminApi("products:write"); if (!auth.user) return auth.response; const id = (await params).id; await prisma.$transaction(async (tx) => { await tx.product.update({ where: { id }, data: { status: "ARCHIVED", deletedAt: new Date() } }); await writeAuditLog(tx, { userId: auth.user.id, action: "PRODUCT_ARCHIVED", entityType: "Product", entityId: id, request }); }); return apiSuccess({ id }); } catch (error) { return handleApiError(error); } }
