import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { CustomerAccessControl } from "@/components/admin/customer-access-control";
import { Badge } from "@/components/ui/badge";
import { requireAdmin } from "@/lib/admin/auth";
import { formatIDR } from "@/lib/formatters";
import { prisma } from "@/lib/prisma";

export default async function CustomerDetail({ params }: { params: Promise<{ id: string }> }) { const admin = await requireAdmin("customers:read"); const customer = await prisma.user.findUnique({ where: { id: (await params).id }, include: { addresses: { orderBy: { isDefault: "desc" } }, orders: { orderBy: { placedAt: "desc" }, take: 10 } } }); if (!customer) notFound(); return <div><AdminPageHeader title={customer.name ?? "Unnamed customer"} description={`${customer.email} · Joined ${new Intl.DateTimeFormat("id-ID", { dateStyle: "long" }).format(customer.createdAt)}`} breadcrumbs={[{ label: "Customers", href: "/admin/customers" }, { label: customer.name ?? customer.email }]} /><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_20rem]"><div className="space-y-6"><Panel title="Orders">{customer.orders.length ? <div className="divide-y divide-[#ded9cf]">{customer.orders.map((order) => <Link href={`/admin/orders/${order.id}`} key={order.id} className="flex justify-between gap-4 py-4 text-sm"><div><p className="font-semibold">{order.orderNumber}</p><p className="text-xs text-muted-foreground">{new Intl.DateTimeFormat("id-ID", { dateStyle: "medium" }).format(order.placedAt)}</p></div><div className="text-right"><p>{formatIDR(Number(order.grandTotal))}</p><Badge variant="outline">{order.status}</Badge></div></Link>)}</div> : <p className="text-sm text-muted-foreground">Belum ada order.</p>}</Panel><Panel title="Addresses"><div className="grid gap-4 md:grid-cols-2">{customer.addresses.map((address) => <address key={address.id} className="border border-[#ded9cf] p-4 text-sm not-italic leading-6"><p className="font-semibold">{address.label} · {address.recipient}</p>{address.line1}<br />{address.district}, {address.city}<br />{address.province} {address.postalCode}<br />{address.phone}</address>)}</div></Panel></div><aside className="h-fit border border-[#ded9cf] bg-[#faf8f3] p-5"><h2 className="font-serif text-2xl">Account access</h2><div className="mt-5">{admin.role === "ADMIN" ? <CustomerAccessControl id={customer.id} initialActive={customer.isActive} initialRole={customer.role} /> : <p className="text-sm text-muted-foreground">Hanya ADMIN dapat mengubah status akun dan role.</p>}</div></aside></div></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border border-[#ded9cf] bg-[#faf8f3] p-5 sm:p-6"><h2 className="font-serif text-2xl">{title}</h2><div className="mt-5">{children}</div></section>; }
