import { AdminDataTable } from "@/components/admin/admin-data-table";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { EntityManager, type EntityField } from "@/components/admin/entity-manager";
import { Badge } from "@/components/ui/badge";
import { requireAdmin } from "@/lib/admin/auth";
import { ADMIN_PAGE_SIZE, parseAdminQuery, type AdminSearchParams } from "@/lib/admin/query";
import { formatIDR } from "@/lib/formatters";
import { prisma } from "@/lib/prisma";

const fields: EntityField[] = [{ name: "code", label: "Code" }, { name: "name", label: "Name" }, { name: "type", label: "Discount type", type: "select", options: [{ value: "PERCENTAGE", label: "Percentage" }, { value: "FIXED_AMOUNT", label: "Fixed amount" }, { value: "FREE_SHIPPING", label: "Free shipping" }] }, { name: "value", label: "Value", type: "number" }, { name: "minSpend", label: "Minimum purchase", type: "number" }, { name: "maxDiscount", label: "Maximum discount", type: "number" }, { name: "usageLimit", label: "Usage limit", type: "number" }, { name: "usagePerUser", label: "Usage per user", type: "number" }, { name: "startsAt", label: "Starts at", type: "datetime-local" }, { name: "endsAt", label: "Ends at", type: "datetime-local" }, { name: "description", label: "Description", type: "textarea" }, { name: "isActive", label: "Active", type: "checkbox" }];
// Voucher defaults are intentionally relative to the current request.
// eslint-disable-next-line react-hooks/purity
export default async function VouchersPage({ searchParams }: { searchParams: AdminSearchParams }) { await requireAdmin("vouchers:read"); const query = await parseAdminQuery(searchParams); const where = { ...(query.q ? { OR: [{ code: { contains: query.q, mode: "insensitive" as const } }, { name: { contains: query.q, mode: "insensitive" as const } }] } : {}), ...(query.status ? { isActive: query.status === "active" } : {}) }; const [rows, total] = await prisma.$transaction([prisma.voucher.findMany({ where, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * ADMIN_PAGE_SIZE, take: ADMIN_PAGE_SIZE }), prisma.voucher.count({ where })]); const defaults = { code: "", name: "", type: "PERCENTAGE", value: 10, minSpend: 0, maxDiscount: 0, usageLimit: 100, usagePerUser: 1, startsAt: new Date(), endsAt: new Date(Date.now() + 30 * 86400000), description: "", isActive: true }; return <div><AdminPageHeader title="Vouchers" description="Atur periode, nilai, minimum pembelian, dan batas pemakaian voucher." breadcrumbs={[{ label: "Vouchers" }]} action={<EntityManager entity="vouchers" fields={fields} defaults={defaults} />} /><AdminDataTable columns={[{ key: "code", label: "Voucher" }, { key: "value", label: "Value" }, { key: "usage", label: "Usage" }, { key: "period", label: "Period" }, { key: "status", label: "Status" }, { key: "action", label: "" }]} rows={rows.map((row) => ({ id: row.id, cells: { code: <div><p className="font-semibold">{row.code}</p><p className="text-xs text-muted-foreground">{row.name}</p></div>, value: row.type === "PERCENTAGE" ? `${Number(row.value)}%` : row.type === "FREE_SHIPPING" ? "Free shipping" : formatIDR(Number(row.value)), usage: `${row.usedCount}/${row.usageLimit ?? "∞"}`, period: `${new Intl.DateTimeFormat("id-ID").format(row.startsAt)} – ${new Intl.DateTimeFormat("id-ID").format(row.endsAt)}`, status: <Badge variant={row.isActive ? "secondary" : "outline"}>{row.isActive ? "Active" : "Inactive"}</Badge>, action: <EntityManager entity="vouchers" fields={fields} defaults={defaults} initial={{ id: row.id, code: row.code, name: row.name, type: row.type, value: Number(row.value), minSpend: row.minSpend ? Number(row.minSpend) : null, maxDiscount: row.maxDiscount ? Number(row.maxDiscount) : null, usageLimit: row.usageLimit, usagePerUser: row.usagePerUser, startsAt: row.startsAt, endsAt: row.endsAt, description: row.description ?? "", isActive: row.isActive }} /> } }))} page={query.page} total={total} totalPages={Math.max(1, Math.ceil(total / ADMIN_PAGE_SIZE))} bulkEndpoint="/api/admin/entities/vouchers" filters={[{ value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }]} /></div>; }
