import { authorizeAdminApi } from "@/lib/admin/auth";
import { writeAuditLog } from "@/lib/admin/audit";
import { apiError, apiSuccess, handleApiError } from "@/lib/api-response";
import { logSellerActivity } from "@/lib/seller/activity";
import { assertSubmissionTransition } from "@/lib/seller/domain";
import { inspectionSchema } from "@/lib/seller/schemas";
import { prisma } from "@/lib/prisma";

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const auth = await authorizeAdminApi("sellers:write"); if (!auth.user) return auth.response; const id = (await params).id; const data = inspectionSchema.parse(await request.json()); const current = await prisma.consignmentSubmission.findUnique({ where: { id } }); if (!current) return apiError("NOT_FOUND", "Submission tidak ditemukan.", 404); if (current.status !== "INSPECTION") return apiError("INVALID_SUBMISSION_STATUS", "Produk belum berada pada tahap inspection.", 409); const next = data.result === "PASSED" ? "READY_TO_LIST" : data.result === "FAILED" ? "REJECTED" : "NEEDS_REVISION"; const reason = data.notes || data.authenticityNote || (data.result === "FAILED" ? "Inspection failed" : "Inspection requires revision"); assertSubmissionTransition({ current: current.status, next, actor: "ADMIN", reason }); if (data.result === "PASSED" && (!Object.values(data.checklist).every(Boolean) || !data.recommendedPrice)) return apiError("INSPECTION_INCOMPLETE", "Checklist dan rekomendasi harga harus lengkap.", 422); const inspection = await prisma.$transaction(async (tx) => { const created = await tx.productInspection.create({ data: { submissionId: id, inspectorId: auth.user.id, result: data.result, checklist: data.checklist, notes: data.notes || null, authenticityNote: data.authenticityNote || null, recommendedPrice: data.recommendedPrice } }); await tx.consignmentSubmission.update({ where: { id }, data: { status: next, revisionReason: next === "NEEDS_REVISION" ? reason : null, rejectionReason: next === "REJECTED" ? reason : null, version: { increment: 1 } } }); await logSellerActivity(tx, { sellerId: current.sellerId, actorUserId: auth.user.id, action: `INSPECTION_${data.result}`, entityType: "ProductInspection", entityId: created.id, metadata: { submissionId: id, nextStatus: next, recommendedPrice: data.recommendedPrice } }); await writeAuditLog(tx, { userId: auth.user.id, action: `CONSIGNMENT_INSPECTION_${data.result}`, entityType: "ConsignmentSubmission", entityId: id, request }); return created; }); return apiSuccess({ id: inspection.id, status: next }, { status: 201 }); } catch (error) { return handleApiError(error); } }
