import { authorizeAdminApi } from "@/lib/admin/auth";
import { writeAuditLog } from "@/lib/admin/audit";
import { apiError, apiSuccess, handleApiError } from "@/lib/api-response";
import { logSellerActivity } from "@/lib/seller/activity";
import { assertSubmissionTransition } from "@/lib/seller/domain";
import { adminSubmissionReviewSchema } from "@/lib/seller/schemas";
import { prisma } from "@/lib/prisma";

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const auth = await authorizeAdminApi("sellers:write"); if (!auth.user) return auth.response; const id = (await params).id; const data = adminSubmissionReviewSchema.parse(await request.json()); if (["READY_TO_LIST", "LISTED"].includes(data.status)) return apiError("DEDICATED_ACTION_REQUIRED", "Gunakan inspection atau publish action.", 409); const current = await prisma.consignmentSubmission.findUnique({ where: { id } }); if (!current) return apiError("NOT_FOUND", "Submission tidak ditemukan.", 404); assertSubmissionTransition({ current: current.status, next: data.status, actor: "ADMIN", reason: data.reason }); if (data.status === "APPROVED" && !data.estimatedPrice) return apiError("PRICE_REQUIRED", "Estimasi harga wajib diisi.", 422); const updated = await prisma.$transaction(async (tx) => { const result = await tx.consignmentSubmission.update({ where: { id, version: current.version }, data: { status: data.status, estimatedPrice: data.estimatedPrice ?? current.estimatedPrice, priceDecision: data.status === "APPROVED" ? "PENDING" : current.priceDecision, revisionReason: data.status === "NEEDS_REVISION" ? data.reason : null, rejectionReason: data.status === "REJECTED" ? data.reason : null, adminNotes: data.adminNotes || current.adminNotes, itemReceivedAt: data.status === "INSPECTION" ? new Date() : current.itemReceivedAt, cancelledAt: data.status === "CANCELLED" ? new Date() : current.cancelledAt, version: { increment: 1 } } }); await logSellerActivity(tx, { sellerId: current.sellerId, actorUserId: auth.user.id, action: `SUBMISSION_${data.status}`, entityType: "ConsignmentSubmission", entityId: id, metadata: { from: current.status, reason: data.reason, estimatedPrice: data.estimatedPrice } }); await writeAuditLog(tx, { userId: auth.user.id, action: `CONSIGNMENT_${data.status}`, entityType: "ConsignmentSubmission", entityId: id, metadata: { from: current.status, reason: data.reason }, request }); return result; }); return apiSuccess({ id, status: updated.status }); } catch (error) { if (error instanceof Error && ["INVALID_SUBMISSION_TRANSITION", "TRANSITION_REASON_REQUIRED"].includes(error.message)) return apiError(error.message, "Perubahan status tidak valid atau memerlukan alasan.", 409); return handleApiError(error); } }
