import Link from "next/link";
import { EyeIcon } from "@phosphor-icons/react/dist/ssr";
import { AdminDataTable } from "@/components/admin/admin-data-table";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { requireAdmin } from "@/lib/admin/auth";
import { ADMIN_PAGE_SIZE, parseAdminQuery, type AdminSearchParams } from "@/lib/admin/query";
import { formatIDR } from "@/lib/formatters";
import { prisma } from "@/lib/prisma";

export default async function CustomersPage({ searchParams }: { searchParams: AdminSearchParams }) { await requireAdmin("customers:read"); const query = await parseAdminQuery(searchParams); const where = { deletedAt: null, ...(query.q ? { OR: [{ name: { contains: query.q, mode: "insensitive" as const } }, { email: { contains: query.q, mode: "insensitive" as const } }, { phone: { contains: query.q, mode: "insensitive" as const } }] } : {}), ...(query.status ? { isActive: query.status === "active" } : {}) }; const [customers, total] = await prisma.$transaction([prisma.user.findMany({ where, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * ADMIN_PAGE_SIZE, take: ADMIN_PAGE_SIZE, include: { orders: { where: { paymentStatus: "PAID" }, select: { grandTotal: true } }, _count: { select: { orders: true, addresses: true } } } }), prisma.user.count({ where })]); return <div><AdminPageHeader title="Customers" description="Lihat akun, alamat, riwayat order, dan status akses customer." breadcrumbs={[{ label: "Customers" }]} /><AdminDataTable columns={[{ key: "customer", label: "Customer" }, { key: "role", label: "Role" }, { key: "orders", label: "Orders" }, { key: "spend", label: "Lifetime spend" }, { key: "status", label: "Status" }, { key: "action", label: "" }]} rows={customers.map((customer) => ({ id: customer.id, cells: { customer: <div><p className="font-semibold">{customer.name ?? "Unnamed"}</p><p className="text-xs text-muted-foreground">{customer.email}</p></div>, role: customer.role, orders: customer._count.orders, spend: formatIDR(customer.orders.reduce((sum, order) => sum + Number(order.grandTotal), 0)), status: <Badge variant={customer.isActive ? "secondary" : "destructive"}>{customer.isActive ? "Active" : "Suspended"}</Badge>, action: <Button asChild size="icon-sm" variant="ghost"><Link href={`/admin/customers/${customer.id}`} aria-label={`View ${customer.email}`}><EyeIcon aria-hidden /></Link></Button> } }))} page={query.page} total={total} totalPages={Math.max(1, Math.ceil(total / ADMIN_PAGE_SIZE))} filters={[{ value: "active", label: "Active" }, { value: "inactive", label: "Suspended" }]} /></div>; }
