import { AdminDataTable } from "@/components/admin/admin-data-table";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { EntityManager, type EntityField } from "@/components/admin/entity-manager";
import { Badge } from "@/components/ui/badge";
import { requireAdmin } from "@/lib/admin/auth";
import { ADMIN_PAGE_SIZE, parseAdminQuery, type AdminSearchParams } from "@/lib/admin/query";
import { prisma } from "@/lib/prisma";

export default async function BrandsPage({ searchParams }: { searchParams: AdminSearchParams }) { const user = await requireAdmin("brands:read"); const query = await parseAdminQuery(searchParams); const where = { deletedAt: null, ...(query.q ? { name: { contains: query.q, mode: "insensitive" as const } } : {}), ...(query.status ? { isActive: query.status === "active" } : {}) }; const [rows, total] = await prisma.$transaction([prisma.brand.findMany({ where, include: { _count: { select: { products: true } } }, orderBy: { name: "asc" }, skip: (query.page - 1) * ADMIN_PAGE_SIZE, take: ADMIN_PAGE_SIZE }), prisma.brand.count({ where })]); const fields: EntityField[] = [{ name: "name", label: "Name" }, { name: "slug", label: "Slug" }, { name: "logoUrl", label: "Logo URL" }, { name: "description", label: "Description", type: "textarea" }, { name: "isFeatured", label: "Featured", type: "checkbox" }, { name: "isActive", label: "Active", type: "checkbox" }]; const defaults = { name: "", slug: "", logoUrl: "", description: "", isFeatured: false, isActive: true }; return <div><AdminPageHeader title="Brands" description="Kelola identitas brand dan penempatan featured." breadcrumbs={[{ label: "Brands" }]} action={user.role === "ADMIN" ? <EntityManager entity="brands" fields={fields} defaults={defaults} /> : null} /><AdminDataTable columns={[{ key: "name", label: "Brand" }, { key: "products", label: "Products" }, { key: "featured", label: "Featured" }, { key: "status", label: "Status" }, { key: "action", label: "" }]} rows={rows.map((row) => ({ id: row.id, cells: { name: <div><p className="font-semibold">{row.name}</p><p className="text-xs text-muted-foreground">/{row.slug}</p></div>, products: row._count.products, featured: row.isFeatured ? "Yes" : "No", status: <Badge variant={row.isActive ? "secondary" : "outline"}>{row.isActive ? "Active" : "Inactive"}</Badge>, action: user.role === "ADMIN" ? <EntityManager entity="brands" fields={fields} defaults={defaults} initial={{ id: row.id, name: row.name, slug: row.slug, logoUrl: row.logoUrl ?? "", description: row.description ?? "", isFeatured: row.isFeatured, isActive: row.isActive }} /> : null } }))} page={query.page} total={total} totalPages={Math.max(1, Math.ceil(total / ADMIN_PAGE_SIZE))} bulkEndpoint={user.role === "ADMIN" ? "/api/admin/entities/brands" : undefined} filters={[{ value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }]} /></div>; }
